DROP TABLE IF EXISTS premiacao;

CREATE TABLE premiacao (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  year VARCHAR(250) NOT NULL,
  title VARCHAR(250) NOT NULL,
  studios VARCHAR(250) DEFAULT NULL,
  producers VARCHAR(250) DEFAULT NULL,
  winner INT DEFAULT NULL
);

